data_params:
  data_paths:
    normal_data_path: 'normal.parquet'
    anom_data_path: 'generated_tsa.parquet'
    meta_data_path: 'meta_data.parquet'
  data_splits:
    train_raito: 0.7
    valid_raito: 0.2
    random_state: 0
  data_scaling: null
model_params:
  model_type: COND_CNN
  batch_size: 64
  lr: 0.002
  meta_hidden_size: 16
  ts_input_size: 2714
  n_meta_layers: 2
  meta_input_size: 3
  epochs: 500
  encoder_params:
    - type: conv
      params:
        in_channels: 1
        out_channels: 64
        kernel_size: 100
        stride: 4
    - type: batch_norm
      params:
        num_features: 64
    - type: relu
    - type: conv
      params:
        in_channels: 64
        out_channels: 64
        kernel_size: 100
        stride: 4
  decoder_params:
    - type: conv_transpose
      params:
        in_channels: 64
        out_channels: 64
        kernel_size: 100
        stride: 4
        output_padding: 2
    - type: batch_norm
      params:
        num_features: 64
    - type: relu
    - type: conv_transpose
      params:
        in_channels: 64
        out_channels: 1
        kernel_size: 100
        stride: 4
        output_padding: 2